### ISSUE TITLE
cross-post config command is throwing exceptions

### ISSUE THREAD

**Issue by mohamedallam1991** [shahednasser/cross-post#28]
cross-post config medium
```
/usr/local/lib/node_modules/cross-post-blog/node_modules/commander/lib/command.js:1030
        throw new Error(executableMissing);
        ^

Error: 'config-medium' does not exist
 - if 'medium' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
 - if the default executable name is not suitable, use the executableFile option to supply a custom name or path
 - searched for local subcommand relative to directory './src/commands/config'
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cross-post-blog/node_modules/commander/lib/command.js:1030:15)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by ethan-rod6** [comment]
Hello @shahednasser, 

I get this error as well. The error occurs while executing the `cross-post config`  with any platforms. Basically the `config` command doesn't work. It seems like the npm package `commander` is somewhat deprecated or something happened to it. Please be kind to refer to this issue as fast as possible.

**Comment by AlbertoBasalo** [comment]
Same here, this is the erro message I got.

```bash
$ cross-post config medium
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'local-path\config-medium'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Thanks
